#!/bin/bash
g++ tree.cpp -o p 
if [  "$?" = "0" ] ; then
	./p < input.txt > output.txt	
	cat output.txt
fi



echo  

#!/bin/bash
g++ tree.cpp -o p 
if [  "$?" = "0" ] ; then
	./p < input.txt > output.txt	
	cat output.txt
fi



echo  

#!/bin/bash
g++ tree.cpp -o p 
if [  "$?" = "0" ] ; then
	./p < input.txt > output.txt	
	cat output.txt
fi



echo  

